name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install
        run: npm install
      
      - name: Build
        env:
          VITE_SUPABASE_URL: https://digavgdgdasnyzijlywn.supabase.co
          VITE_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpZ2F2Z2RnZGFzbnl6aWpseXduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ2NTk3ODIsImV4cCI6MjEwMDIzNTc4Mn0.-YzCcI2DzbjoOOc8vAHug8jw1VCzfVhJs-P4HDodTH4
          VITE_ADMIN_PASSWORD: Army@2026
        run: npm run build
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
